{% set name = "tokenizers" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0bcfa45cfd66e6aa379c7362d56a77f66a195fd06bc38ec912ca3d63c03d3b8

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib64/libgcc_s.so.1  # [linux]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools-rust
    - setuptools
  run:
    - python
    - libgcc-ng                                                  # [linux]

test:
  imports:
    - tokenizers
    - tokenizers.models
    - tokenizers.decoders
    - tokenizers.normalizers
    - tokenizers.pre_tokenizers
    - tokenizers.processors
    - tokenizers.trainers
    - tokenizers.implementations

about:
  home: https://github.com/huggingface/tokenizers
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Fast State-of-the-Art Tokenizers optimized for Research and Production

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
