{% set name = "tokenizers" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bacaeb3621055aba9b5158a21dc8b5d80f65724ff47f414f9d06f1e087668d61

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  missing_dso_whitelist:
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib64/libgcc_s.so.1  # [linux]
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools-rust
    - setuptools
  run:
    - python
    - libgcc-ng                                                  # [linux]

test:
  imports:
    - tokenizers
    - tokenizers.models
    - tokenizers.decoders
    - tokenizers.normalizers
    - tokenizers.pre_tokenizers
    - tokenizers.processors
    - tokenizers.trainers
    - tokenizers.implementations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/tokenizers/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Fast State-of-the-Art Tokenizers optimized for Research and Production
  dev_url: https://github.com/huggingface/tokenizers

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - ndmaxar
    - setu4993
